[package]
edition = "2021"
name = "client"
version = "0.1.0"

[build-dependencies]
tauri-build = { version = "1.4.0", features = [] }

[dependencies]
tauri = { version = "1.4.1", features = ["shell-open"] }

[features]
custom-protocol = ["tauri/custom-protocol"]
default = ["custom-protocol"]
